services:
    php:
        build: ./docker/php
        restart: on-failure
        volumes:
            - ./:/var/www
        ports:
            - "9000:9000"
        networks:
            - symfony

    nginx:
        image: nginx:stable-alpine
        restart: on-failure
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - symfony

    db:
        image: mysql:8.0.33
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql/
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - symfony

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin
        restart: on-failure
        ports:
            - "8090:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        networks:
            - symfony

    mailpit:
        image: axllent/mailpit
        container_name: mailpit
        restart: on-failure
        volumes:
            - ./data:/data
        ports:
            - 8025:8025
            - 1025:1025
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATABASE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
        networks:
            - symfony

networks:
    symfony:

volumes:
    dbdata:
        driver: local
